### ISSUE TITLE
Clarity required on domain and search settings for esx_dnsconfig type

### ISSUE THREAD

**Issue by gjngeldenhuis** [vmware/vmware-vcenter#167] opened 2016-05-13 15:33 UTC
The esx_dnsconfig allows you to set both:

- domain_name
- search_domain

On Ubuntu or CentOS the man page for resolv.conf reads:

> The domain and search keywords are mutually exclusive.  If more than one instance of these keywords is present, the last instance wins.

Knowing whether this is true in ESXi would be very useful. If this is the case the provider can ensure that the values are mutually exclusive and that you can't set both from puppet. Protecting you from yourself.

**Comment by gjngeldenhuis** [comment] 2016-05-13 15:42
Some further reading:
http://pubs.vmware.com/vsphere-55/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.host.DnsConfig.html

**Comment by klevron1** [comment] 2016-05-16 21:16
From what I've seen, domain_name is used in conjunction with host_name to set the FQDN of the host.
It is not used to set any options in the host's resolver configuration.

They are not mutually exclusive parameters.

**Comment by rbbrown** [comment] 2016-07-05 19:39
@gjngeldenhuis, as you wrote earlier "Knowing whether this is true in ESXi would be very useful." So, we know -- the reference you provided shows that ESXi is different from Linux, and the values are not mutually exclusive. 

If the issue is resolved, please close it. If not, please follow up with remaining concerns.

**Comment by gjngeldenhuis** [comment] 2016-07-05 20:04
@rbbrown I will close it tomorrow, I need to update the documentation for the module to reflect this. Thank you for chasing.

**Closed** 2016-07-06 12:39 UTC
